export { default as Footer } from "./Footer.astro"
export { default as Hero } from "./Hero.astro"
export { default as OtherProducts } from "./OtherProducts.astro"
export { default as ProductDetails } from "./ProductDetails.astro"
export { default as ThreeImageGallery } from "./ThreeImageGallery.astro"
